config/routes.rb
Hangyourboots::Application.routes.draw do

  root :to => "login#show"
  match '/tos', :to => redirect('/tos.html')

  resources :users
  resources :houses do
    resources :commitments, :only => [:create, :destroy]
  end

  resources :invitations
  resources :cohorts

  get 'auth/facebook', :as => 'login'

  match 'join', to: 'login#new', :as => 'join', :via => 'post'

  match 'auth/:provider/callback/', to: 'sessions#create'
  match 'auth/failure', to: "login#show"
  match 'signout', to: 'sessions#destroy', as: 'signout'

  post '/houses/:id/commitments/create' => 'commitments#create'

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
	attr_accessible :name
	has_many :users
	has_many :houses
	has_many :invitations
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  respond_to :html
  before_filter :authorize_user

  def show
    @cohort = Cohort.find(params[:id])
  end

  def index
    @cohorts = Cohort.all
  end

  def new
    @cohort = Cohort.new
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    if @cohort.update_attributes(params[:cohort])
      flash[:notice] = "Updated cohort"
      redirect_to cohorts_path
    else
      flash[:alert] = "Something went wrong"
      render 'edit'
    end
  end

  def create
    @cohort = Cohort.create(params[:cohort])
    flash[:notice] = "Successfully created cohort"
    respond_with(@cohort)
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    if @cohort.destroy
      flash[:notice] = "Successfully deleted cohort"
      redirect_to cohorts_path
    end
  end

  private
  def authorize_user
    unless current_user && current_user.is_admin?
      redirect_to root_url
    end
  end
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
    <%= f.label :name, "Cohort name" %>
    <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/cohorts/edit.html.erb
<%= render 'form' %>

app/views/cohorts/index.html.erb
<div>
<%= link_to "New cohort", new_cohort_path %>
</div>


<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cohorts.each do |i| %>
  <tr>
    <td><%= i.name %></td>
    <td><%= link_to 'Show', cohort_path(i) %></td>
    <td><%= link_to 'Edit', edit_cohort_path(i) %></td>
    <td><%= link_to 'Destroy', i, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/cohorts/new.html.erb
<%= render 'form' %>

app/views/cohorts/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= @cohort.name %></td>
    <td><%= link_to 'Edit', edit_cohort_path(@cohort) %></td>
    <td><%= link_to 'Destroy', @cohort, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</table>

<div>
<%= link_to "New invitation", new_invitation_path %>
</div>
<div>
<%= link_to "Back", cohorts_path %>
</div>