config/routes.rb
Hangyourboots::Application.routes.draw do

  root :to => "login#show"
  match '/tos', :to => redirect('/tos.html')

  resources :users
  resources :houses do
    resources :commitments, :only => [:create, :destroy]
  end

  resources :invitations
  resources :cohorts

  get 'auth/facebook', :as => 'login'

  match 'join', to: 'login#new', :as => 'join', :via => 'post'

  match 'auth/:provider/callback/', to: 'sessions#create'
  match 'auth/failure', to: "login#show"
  match 'signout', to: 'sessions#destroy', as: 'signout'

  post '/houses/:id/commitments/create' => 'commitments#create'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	attr_accessible :code, :expires_at, :cohort_id

	has_many :users
	has_many :houses
	belongs_to :cohort

	def self.valid_code?(code)
		self.find_by_code(code).try(:active?)
	end

	def expired?
		Time.now >= expires_at
	end

  def active?
    Time.now < expires_at
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  respond_to :html
  before_filter :authorize_user

  def show
    @invitation = Invitation.find(params[:id])
  end

  def index
    @invitations = Invitation.all
  end

  def new
    @invitation = Invitation.new
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  def update
    @invitation = Invitation.find(params[:id])
    if @invitation.update_attributes(params[:invitation])
      flash[:notice] = "Updated invitation"
      redirect_to invitations_path
    else
      flash[:alert] = "Something went wrong"
      render 'edit'
    end
  end

  def create
    @invitation = Invitation.create(params[:invitation])
    flash[:notice] = "Successfully created invitation"
    respond_with(@invitation)
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    if @invitation.destroy
      flash[:notice] = "Successfully deleted invitation"
      redirect_to invitations_path
    end
  end

  private
  def authorize_user
    unless current_user && current_user.is_admin?
      redirect_to root_url
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
	def	cohort_options
		Cohort.all.collect do |cohort|
			[cohort.name, cohort.id]
		end
	end
end

app/views/invitations/_form.html.erb
<%= form_for @invitation do |f| %>
    <%= f.label :code, "Invitation code" %>
    <%= f.text_field :code %>
    <%= f.label :cohort, "Cohort" %>
    <%= select(:invitation, :cohort_id, cohort_options) %>
    <%= f.label :expires_at, "Expiration date" %>
    <%= date_select "invitation", "expires_at" %>
  <%= f.submit "Submit" %>
<% end %>

app/views/invitations/index.html.erb
<div>
<%= link_to "New invitation", new_invitation_path %>
</div>


<table>
  <tr>
    <th>Code</th>
    <th>Cohort</th>
    <th>Expiration date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |i| %>
  <tr>
    <td><%= i.code %></td>
    <td><%= i.cohort.name %></td>
    <td><%= i.expires_at.strftime("%b %d %Y") %></td>
    <td><%= link_to 'Show', invitation_path(i) %></td>
    <td><%= link_to 'Edit', edit_invitation_path(i) %></td>
    <td><%= link_to 'Destroy', i, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/invitations/show.html.erb
<table>
  <tr>
    <th>Code</th>
    <th>Expiration date</th>
    <th>Cohort</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= @invitation.code %></td>
    <td><%= @invitation.expires_at.strftime("%b %d %Y") %></td>
    <td><%= @invitation.cohort.name %></td>
    <td><%= link_to 'Edit', edit_invitation_path(@invitation) %></td>
    <td><%= link_to 'Destroy', @invitation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</table>

<div>
<%= link_to "Back", invitations_path %>
</div>