config/routes.rb
Hangyourboots::Application.routes.draw do

  root :to => "login#show"
  match '/tos', :to => redirect('/tos.html')

  resources :users
  resources :houses do
    resources :commitments, :only => [:create, :destroy]
  end

  resources :invitations
  resources :cohorts

  get 'auth/facebook', :as => 'login'

  match 'join', to: 'login#new', :as => 'join', :via => 'post'

  match 'auth/:provider/callback/', to: 'sessions#create'
  match 'auth/failure', to: "login#show"
  match 'signout', to: 'sessions#destroy', as: 'signout'

  post '/houses/:id/commitments/create' => 'commitments#create'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Hang Your Boots", '#', :class => 'brand' %>

<ul class="nav">
  <% if current_user %>
    <li><%= link_to "Hacker Houses", houses_path %></li>
    <li><%= link_to "Potential Roommates", users_path %></li>
  <% end %>
  <% if current_user.try(:is_admin?) %>
    <li><%= link_to "Cohorts", cohorts_path %></li>
    <li><%= link_to "Invitations", invitations_path %></li>
  <% end %>
</ul>

<div class="pull-right">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out",
                signout_path,
                id: "sign_out",
                :class => "btn btn-mini btn-success" %>
  <% else %>
    <%= link_to "Sign in with Facebook",
                "/auth/facebook",
                id: "sign_in",
                :class => "btn btn-mini btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hang Your Boots" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
          <%= render 'layouts/navigation' %>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/login.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hang Your Boots" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
          <%= render 'layouts/navigation' %>
      </nav>
    </header>
    <!-- carousel was here -->
    <!-- <div id="main" role="main"> -->
      <!-- <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12"> -->
              <%= render 'layouts/messages' %>
              <%= yield %>
              <%= render 'homepage_info' %>
            <!-- </div>
          </div> -->
          <!-- FOOTER -->
          <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>&copy; 2012 Hang Your Boots.</p>
          </footer>
        <!-- </div> -->
      <!-- </div> --> <!--! end of .container -->
    <!-- </div> --> <!--! end of #main -->
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
  </body>
</html>